name: Preview Deploy
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Unit Test
        run: npm run test
  Deploy_Vercel:
    needs: [Unit_Test]
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ vercel-preview.PREVIEW_URL }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Deploy to Vercel Action
        uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GH_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          #          PRODUCTION: false # Don't deploy to production environment
          #          alias-domains: | #Optional
          #            staging.angular.vercel-action.amond.dev
          #            pr-{{PR_NUMBER}}.angular.vercel-action.amond.dev
  E2E_Test:
    needs: [Deploy_Vercel]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Cypress Test
        run: npm run cypress